Metrics/AbcSize:
    Enabled: false
Metrics/CyclomaticComplexity:
    Enabled: false
Metrics/LineLength:
    Enabled: false
Metrics/MethodLength:
    Enabled: false
Metrics/PerceivedComplexity:
    Enabled: false
Style/Documentation:
    Enabled: false
Style/IndentArray:
    Enabled: false
Style/IndentHash:
    Enabled: false
Style/IndentationWidth:
    Enabled: false
Style/Tab:
    Enabled: false
